# Spring datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_rest_server_data?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Kljukec123#

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    user:
      name: root
      password: root
server:
  address: localhost
  port: 6050

app:
  captcha:
    url: https://www.google.com/recaptcha/api/siteverify
    secret: 6Ldmgz0aAAAAALnuLNRL23IOrnXSQ_zGWioBI0Kc
